export const COLORS = {
  PRIMARY_BLUE: {
    DEFAULT: '#007fff',
    SHADE: '#006cd8',
    MEDIUM_TINT: '#3399ff',
    LIGHT_TINT: '#e5f2ff',
    ULTRALIGHT_TINT: '#e5f2ff',
  },
  MONOCHROME: {
    BLACK: '#1b191b',
    WHITE: '#ffffff',
    DEFAULT: '#687481',
    SHADE: '#58626d',
    DARK_TINT: '#a4acb3',
    MEDIUM_TINT: '#e3e6e8',
    LIGHT_TINT: '#f8f9fb',
  },
  GREEN: {
    DEFAULT: '#00b602',
    SHADE: '#009402',
    MEDIUM_TINT: '#33c535',
    LIGHT_TINT: '#e5f7e5',
  },
  RED: {
    DEFAULT: '#ee0000',
    SHADE: '#cc0000',
    MEDIUM_TINT: '#f13333',
    LIGHT_TINT: '#fccccc',
    ULTRALIGHT_TINT: '#fde5e5',
  },
  YELLOW: {
    DEFAULT: '#ffdd00',
    SHADE: '#ebcb00',
    MEDIUM_TINT: '#ffe74c',
    LIGHT_TINT: '#fffbe5',
  },
  ORANGE: {
    DEFAULT: '#f5a623',
    SHADE: '#dc931b',
    MEDIUM_TINT: '#f7b84f',
    LIGHT_TINT: '#fef6e9',
  },
  DATA_VISUALIZATION: {
    DV1: '#67d5b5',
    DV2: '#8b70cd',
    DV3: '#76a5e3',
    DV4: '#ee7785',
    DV5: '#f7d77c',
    DV6: '#88e2f3',
    DV7: '#d599ff',
    DV8: '#b2e67d',
    DV9: '#f9ae7d',
    DV10: '#ccd0db',
    BUILD_COVER: '#62adfc',
    OVERLAPPING: '#4f8ac9',
    SCOPE_COVER: '#aed4fd',
  },
};
export const FONTS = {
  SEMI_BOLD: "'OpenSans-Semibold', sans-serif",
  LIGHT: "'OpenSans-Light', sans-serif",
  REGULAR: "'OpenSans', sans-serif",
  COND_BOLD: "'OpenSansCondBold', sans-serif",
};
